package com.lld.lowleveldesign.carRentalSystem;

public enum ReservationType {
    HOURLY, DAILY, WEEKLY, MONTHLY, YEARLY, ONE_WAY, ROUND_TRIP, MULTI_CITY, OPEN_JAW, GROUP, CORPORATE, GOVERNMENT, LONG_TERM, SHORT_TERM, PEAK_SEASON, OFF_SEASON, LAST_MINUTE, ADVANCE_BOOKING, FLEXIBLE_BOOKING, NON_REFUNDABLE_BOOKING
}
